name: CI/CD
on:
  push:
    branches: [main]
    paths:
      - 'go.*'
      - '**.go'

jobs:
  run:
    name: Runs the CI/CD for the repository.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: echo "lint"

      - name: Test
        run: echo "test"

      - name: Notify Slack
        if: always()
        uses: jmpa-oss/job-to-slack@v0.0.1
        with:
          webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
          status: ${{ job.status }}
