name: template-cleanup
on:
  push:
    branches: [main]

jobs:
  run:
    name: Cleans up the repository when a child is first created; triggers from the first commit to the repository.
    runs-on: ubuntu-20.04
    if: github.event.repository.name != 'root-template'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-southeast-2

      - name: Rename template?
        run: ./bin/rename-template.sh
        env:
          PARENT_TEMPLATE: root-template

      - name: Cleanup
        run: ./bin/template-cleanup.sh

      - name: Commit?
        run: |
          [[ -z $(git status --porcelain) ]] && { echo "no changes to commit; skipping"; exit 0; }
          git config user.name 'GitHub Actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Template cleanup" # no 'skip ci' here, so the README.md is updated.
          git push origin HEAD:main

      - name: Notify Slack
        if: always()
        uses: jmpa-oss/job-to-slack@v0.0.1
        with:
          webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
          status: ${{ job.status }}
