name: update
on:
  repository_dispatch:
    types: [update]

jobs:
  run:
    name: Updates repository with changes from parent template.
    runs-on: ubuntu-20.04
    if: github.event.repository.name != 'root-template'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Update
        run: |
          git config user.name 'GitHub Actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          ./bin/update.sh # commit occurs in the file.
          git push origin HEAD:main
        env:
          PARENT_TEMPLATE: root-template

      - name: Notify Slack
        if: always()
        uses: jmpa-oss/job-to-slack@v0.0.1
        with:
          webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
          status: ${{ job.status }}
